server:
  port: 8081

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/imooc-dubbo-item?characterEncoding=utf-8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: item-service
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://192.168.202.61:2181?backup=192.168.202.62:2181,192.168.202.63:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: 20881
  packageName: com.imooc.service.impl  #服务暴露与发现消费所在的package